# Generated by Django 3.0.4 on 2020-04-24 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 19, 33, 33, 737744)),
        ),
    ]
